services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Symfony\Component\HttpFoundation\Request:
        factory: ['Symfony\Component\HttpFoundation\Request', 'createFromGlobals']
        public: true
    Symfony\Component\HttpFoundation\Response:
        public: true
    Hashids\Hashids:
        arguments: ['%salt%', '%minLength%']
    App\DbConfig\MySqli: ~
    League\Plates\Engine:
        arguments: ['%viewsDir%']
    App\View\FrontRenderInterface:
        class: 'App\View\FrontRender'
    App\Route\ErrorView:
        public: true
    DB\Model\:
        resource: '../database/Model/*'
    App\Controllers\:
        resource: "../src/Controllers/*"
        public: true