services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Symfony\Component\HttpFoundation\Request:
        factory: ['Symfony\Component\HttpFoundation\Request', 'createFromGlobals']
        public: true
    Symfony\Component\HttpFoundation\Response:
        public: true
    # session_storage:
    #     class: 'Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage'
    # Symfony\Component\HttpFoundation\Session\SessionInterface:
    #     class: 'Symfony\Component\HttpFoundation\Session\Session'
       # arguments: ['@session_storage']
    Hashids\Hashids:
        arguments: ['%salt%', '%minLength%']
    League\Plates\Engine:
        arguments: ['%viewsDir%']
    App\DbConfig\MySqli: ~
    Symfony\Component\HttpFoundation\Session\SessionInterface:
        factory: ['App\Util\AppSession', 'getInstance']
    App\View\FrontRenderInterface:
        class: 'App\View\FrontRender'
    App\Route\ErrorView:
        public: true
    DB\Model\:
        resource: '../database/Model/*'
    App\Controllers\:
        resource: "../src/Controllers/*"
        public: true