services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Symfony\Component\HttpFoundation\Request:
        public: true
    Symfony\Component\HttpFoundation\Response:
        public: true
    League\Plates\Engine:
        arguments: ['%viewsDir%']
    DB\Model\:
        resource: '../database/Model/*'
    App\Controllers\:
        resource: "../src/Controllers/*"
        public: true