services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Symfony\Component\HttpFoundation\Request:
        factory: ['Symfony\Component\HttpFoundation\Request', 'createFromGlobals']
        public: true
    Symfony\Component\HttpFoundation\Response:
        public: true
    Hashids\Hashids:
        arguments: ['%salt%', '%minLength%']
    League\Plates\Engine:
        arguments: ['%viewsDir%']
    App\DbConfig\MySqli:
        lazy: true
    session_storage:
        class: 'Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage'
        arguments: ['%session_options%']
    session_attrbag:
        class: 'Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag'
    Symfony\Component\HttpFoundation\Session\SessionInterface:
        class: 'Symfony\Component\HttpFoundation\Session\Session'
        arguments: ['@session_storage', '@session_attrbag']
    App\Util\AppSession:
        arguments: ['@Symfony\Component\HttpFoundation\Session\SessionInterface', '@Symfony\Component\HttpFoundation\Request','%session.maxlife%']
    App\View\FrontRenderInterface:
        class: 'App\View\FrontRender'
        lazy: true
    App\Route\ErrorView:
        public: true
        lazy: true
    DB\Model\:
        resource: '../database/Model/*'
    App\Middlewares\:
        resource: '../src/Middlewares/*'
        public: true
    App\Controllers\:
        resource: "../src/Controllers/*"
        public: true